### ISSUE TITLE
Problème à l'installation

### ISSUE THREAD

**Issue by NikoWoot** [thecodingmachine/utils.cache.memcached-cache#2]
Bonjour, 
Lors de ma tentative d'installation de utils.cache.memcached-cache, le dossier arrive bien dans le dossier /vendor mais n'est pas ajouté dans le Mouf-UI, je pense que le plugin n'est pas à jour.

**Comment by moufmouf** [comment]
De toute évidence, ce paquet n'a pas été correctement migré de la V1 de Mouf. Je regarde ça tout de suite.

**Comment by moufmouf** [comment]
Ok, c'est réglé.
Il y a maintenant un installeur à faire tourner juste après l'installation du paquet (à partir de l'écran d'accueil de Mouf).

Il créé une instance par défaut du service de cache (memcachedCacheService).
Tu peux chercher cette instance dans les instances disponibles et la reconfigurer comme tu souhaites si les paramètres par défaut ne te suffisent pas.

**Comment by NikoWoot** [comment]
La page d'installation n'effectue aucune action. J'ai fait l'essai sur Apache2 et Nginx.

**Comment by moufmouf** [comment]
Ok je regarde cet après-midi.

**Comment by moufmouf** [comment]
Fixed. Effectue un "composer update" pour récupérer la dernière version, puis dans "Project > Installation tasks", relance l'installeur du packet memcache à la main (bouton "Reinstall").

Tu devrais voir apparaître l'instance "memcachedCacheService" dans la liste des instances.
